name: Build and Publish

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
    - '**'
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version information from deps.list
      id: vars
      run: |
        PROTOBUF_VERSION=$(grep "^PROTOBUF_VERSION=" deps.list | cut -d '=' -f 2)
        GO_IMAGE_VERSION=$(grep "^GO_IMAGE_VERSION=" deps.list | cut -d '=' -f 2)
        PYTHON_VERSION=$(grep "^PYTHON_VERSION=" deps.list | cut -d '=' -f 2)

        # Output the tag format as {PROTOBUF_VERSION}-go{GO_IMAGE_VERSION}-python{PYTHON_VERSION}
        IMAGE_TAG="${PROTOBUF_VERSION}-go${GO_IMAGE_VERSION}-python${PYTHON_VERSION}"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build the Docker image
      run: make build

    - name: Tag and Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/leedigitalworks/protobuf-docker
        docker tag protobuf-docker:latest $IMAGE_NAME:${{ env.IMAGE_TAG }}
        docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
